source 'https://rubygems.org'
ruby '3.2.0'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.8'
gem 'rack-cors', '~> 2.0'
gem 'jbuilder', '~> 2.11'

# Reduces boot times through caching
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
end
